<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" Version="6.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Deployment\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Schemas\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
	<EmbeddedResource Include="Tables\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Views\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Functions\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="StoredProcedures\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Triggers\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="ReplicationPrimary\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
