<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Npgsql.Json.NET" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transactions.Repository.Abstractions\Transactions.Repository.Abstractions.csproj" />
  </ItemGroup>

</Project>
